### ISSUE TITLE
Đọc danh sách từ file

### ISSUE THREAD

**Issue by uongsuadaubung** [ProCoderEris/vn-badwords#1]
Không phải chê, chỉ là mong bạn đọc từ file ra thì sẽ đỡ cực hơn khi update thôi.  

![image](https://user-images.githubusercontent.com/40235045/194719717-97ed059f-621d-427a-8359-ded2ec262692.png)
![image](https://user-images.githubusercontent.com/40235045/194719756-ee3e41ee-b49a-4a31-8344-577586a16a2c.png)
  
hoặc xịn hơn nữa thì có thể gửi request đến server của bạn lấy cái list về, mình ví dụ vậy thôi chứ cũng chả biết có được không nếu như nó là 1 cái thư viện trên npm, nhưng chắc là được

**Comment by ProCoderEris** [comment]
em sẽ ghi nhận ý kiến của bác nhé. bác có thể tạo pull requests

**Comment by hqtruong27** [comment]
Mình thấy đoạn Regex có thêm flag `gm` nếu test nhiều dòng liên tiếp sẽ trả ra true -> false -> true, mình nghĩ nên bỏ flag đó đi.

**Comment by ProCoderEris** [comment]
> Mình thấy đoạn Regex có thêm flag `gm` nếu test nhiều dòng liên tiếp sẽ trả ra true -> false -> true, mình nghĩ nên bỏ flag đó đi.

Dạ vâng ạ
