### ISSUE TITLE
Hỗ trợ TypeScript

### ISSUE THREAD

**Issue by samhwang** [ProCoderEris/vn-badwords#7]
Hi Sáng,

Mình muốn sử dụng package này trong dự án TS của mình mà không được vì không có types. Bạn có dự định hỗ trợ TS không? Mình sẵn sàng làm 1 PR nếu cần thiết.

**Comment by ProCoderEris** [comment]
Em không giỏi về TS ạ, nếu được thì bác cứ làm đi ạ, có gì em tham khảo nhé

Vào 14:11, Th 4, 22 thg 3, 2023 samhwang ***@***.***> đã viết:
